/*
 * MSYSTICK_Program.c
 *
 *  Created on: Jun 20, 2023
 *      Author: Mohamed Said
 */


#include"BIT_MATH.h"
#include"MSYSTICK_Interface.h"
#include"MSYSTICK_Private.h"
#include"MSYSTICK_CNFG.h"

static void (*ptf)(void);

static u8 SYSTICK_SINGLE_PERIODIC_INT;


void MSYSTICK_VoidInit(void)
{
	/*set the clock source*/
	switch(SYSTICK_CLOCK_SOURCE)
	{
	case SYSTICK_CLOCK_AHB: 	SET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_CLKSRC); break;
	case  SYSTICK_CLOCK_AHB_8:	CLR_BIT(MSYSTICK_REG->CTRL,STK_CTRL_CLKSRC); break;
	}
}
void MSYSTICK_VoidStopTimer(void)
{
	CLR_BIT(MSYSTICK_REG->CTRL,STK_CTRL_ENABLE);
}
void MSYSTICK_VoidSetBusyDelay(u32 Copy_U32LoadValue)
{
	MSYSTICK_REG->LOAD=Copy_U32LoadValue;
	MSYSTICK_REG->VAL=VALUE_ZERO;
	CLR_BIT(MSYSTICK_REG->CTRL,STK_CTRL_TICK_INT);
	SET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_ENABLE);
	while (GET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_COUNTFLAG)==VALUE_ZERO);
	CLR_BIT(MSYSTICK_REG->CTRL,STK_CTRL_ENABLE);
}
void MSYSTICK_VoidSetIntervalSingle(u32 Copy_U32LoadValue)
{
	SYSTICK_SINGLE_PERIODIC_INT	=SYSTICK_SINGLE_INT;
	/*SETTING THE LOAD VALUE TO THE NUMBER OF PROCESSOR CYCLES WE WANT*/
	MSYSTICK_REG->LOAD=Copy_U32LoadValue;
	/*CLEARING THE VALUE REGISTER AND THE COUNTR FLAG*/
	MSYSTICK_REG->VAL=VALUE_ZERO;
	/*SETTING THE INTERRUPT ENABLE*/
	SET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_TICK_INT);
	/*ENABLE THE COUNTER TO START COUNTING*/
	SET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_ENABLE);
}
void MSYSTICK_VoidSetIntervalPerodic(u32 Copy_U32LoadValue)
{
	SYSTICK_SINGLE_PERIODIC_INT	=SYSTICK_PERODIC_INT;
	/*SETTING THE LOAD VALUE TO THE NUMBER OF PROCESSOR CYCLES WE WANT*/
	MSYSTICK_REG->LOAD=Copy_U32LoadValue;
	/*CLEARING THE VALUE REGISTER AND THE COUNTR FLAG*/
	MSYSTICK_REG->VAL=VALUE_ZERO;
	/*SETTING THE INTERRUPT ENABLE*/
	SET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_TICK_INT);
	/*ENABLE THE COUNTER TO START COUNTING*/
	SET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_ENABLE);
}
u32  MSYSTICK_U32GetElabsedTimer(void)
{
	return MSYSTICK_REG->LOAD-MSYSTICK_REG->VAL;
}
u32  MSYSTICK_U32GetRemainingTime(void)
{
	return MSYSTICK_REG->VAL;
}
void MSYSTICK_VoidSetCallBack(void (*ptr)(void))
{
	ptf=ptr;
}

void SysTick_Handler(void)
{
	if(SYSTICK_SINGLE_PERIODIC_INT==SYSTICK_SINGLE_INT)
	{
		/*stop timer*/
		CLR_BIT(MSYSTICK_REG->CTRL,STK_CTRL_ENABLE);
	}
	ptf();
	/*CLEAR INTERRUPT FLAG*/
	GET_BIT(MSYSTICK_REG->CTRL,STK_CTRL_COUNTFLAG);
}


